eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
server:
  port: 8080

spring:
  application:
    name: apigateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            exposedHeaders: "*"
      routes:
        - id: paymentservice
          uri: http://18.222.128.181:8070
          predicates:
            - Path=/paymentservice/**
          filters:
            - RewritePath=/paymentservice(?<segment>/?.*), $\{segment}

        - id: authenticationservice
          uri: http://18.222.128.181:8095
          predicates:
            - Path=/authenticationservice/**
          filters:
            - RewritePath=/authenticationservice(?<segment>/?.*), $\{segment}

        - id: emailservice
          uri: http://18.222.128.181:8075
          predicates:
            - Path=/emailservice/**
          filters:
            - RewritePath=/emailservice(?<segment>/?.*), $\{segment}

        - id: appointmentservice
          uri: http://18.222.128.181:8097
          predicates:
            - Path=/appointmentservice/**
          filters:
            - RewritePath=/appointmentservice(?<segment>/?.*), $\{segment}

        - id: userservice
          uri: http://18.222.128.181:8083
          predicates:
            - Path=/userservice/**
          filters:
            - RewritePath=/userservice(?<segment>/?.*), $\{segment}

        - id: productwebapp
          uri: http://18.222.128.181:4200
          predicates:
            - Path=/**
          filters:
            - RewritePath=/productwebapp(?<segment>/?.*), $\{segment}